version: '3.8'

services:
  alpine-01:
    image: alpine:latest
    deploy:
      replicas: 1

  alpine-02:
    image: alpine:latest
    deploy:
      replicas: 1

  busybox-01:
    image: busybox:latest
    command: sh -c "top"
    deploy:
      replicas: 1
